print("Courses are:")
print("             ")
print("1)What is Data Science")
print("2)Tools for data science")
print("3)Data Science Methodology")
print("4)Python for data science and ai and development")
print("5)Python project for data science ")
print("6)Database and sql for data science with python")
print("7)Data analysis with python")
print("8)Data visulization with python")
print("9)Machine learning with python")
print("10)Applied data science Capstone")
